# Generated by Django 2.2.7 on 2019-12-03 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0007_auto_20191203_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 2, 29, 5, 746544)),
        ),
    ]
